micronaut:
  application:
    name: kafkaUtils
  server:
    context-path: /api
    read-timeout: 180
  security:
    enabled: true
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

jackson:
  serialization-inclusion: non_null

password-encoder:
  slat: $2b$10$SwKT/LWOb86Crn6OCzheru

dbcommons:
  host: localhost
  port: 3306
  username: root
  password: mysql

r2dbc:
  datasources:
    default:
      url: 'r2dbc:mysql://${dbcommons.host}:${dbcommons.port}/kafka_utils'
      username: '${dbcommons.username}'
      password: '${dbcommons.password}'
      schema-generate: none

flyway:
  datasources:
    default:
      enabled: true
      url: 'jdbc:mysql://${dbcommons.host}:${dbcommons.port}/kafka_utils'
      username: '${dbcommons.username}'
      password: '${dbcommons.password}'
