micronaut:
  application:
    name: kafkaUtils
  server:
    context-path: /api
    read-timeout: 180
  security:
    enabled: false
#    authentication: bearer
#    token:
#      jwt:
#        signatures:
#          secret:
#            generator:
#              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'

database:
  host: localhost
  port: 5433
  username: postgres
  password: postgres

datasources:
  default:
    url: 'jdbc:postgresql://${database.host}:${database.port}/kafka_utils'
    driverClassName: org.postgresql.Driver
    username: '${database.username}'
    password: '${database.password}'
    schema-generate: none
    dialect: POSTGRES

flyway:
  datasources:
    default:
      enabled: true
r2dbc:
  datasources:
    default:
      url: 'r2dbc:postgresql://${database.host}:${database.port}/kafka_utils'
      username: '${database.username}'
      password: '${database.password}'
      schema-generate: none

